#!/usr/bin/env zsh

local source_type
local plugin_id=${1}

# detec of what type of mirrorer I should use
case $1 in
	(@*/*) source_type=${${1/@/}:h} ;;
	(*/*) source_type=github ;;
esac

plugin_id=${1}
shift


local -a explicit_file_to_load=()
while [[ -n "$@" ]]; do
    case $1 in
		(wait*)
			wait_condition=${1/wait/}
		;;
        (pick*)
            explicit_file_to_load+=(${1/pick/})
        ;;
    esac
    shift
done

# clone repos if they are not exist
if ! .is-plugin-installed ${plugin_id}; then
	export ZU_EVENT_NEW_PLUGINS=true
	revolver start "Adding $1 plugin..."

	.zu-fn-sources-${source_type}-clone ${plugin_id} 2>> ~/.zshrc.log
	revolver stop
	echo "${fg_bold[cyan]}✔ ${fg_bold[blue]}$1${reset_color} installed "
fi

# add plugin dir to fpath to detect completions
local plugin_path=${ZUTILS[PLUGINS_DIR]}/${plugin_id/\//--}
fpath+=(${plugin_path})

if [[ "${wait_condition}" == "idle" ]]; then
	eval ".zsh-defer.${1/\//--}.source() {
		source $1;
		zsh_loaded_plugins+=( "${plugin_id}" );
	}"
fi

if [[ -n "${(@)explicit_file_to_load}" ]]; then
	# if we picked up explicit files we need to add full path
	explicit_file_to_load=( ${explicit_file_to_load/#/${plugin_path}\/} )
fi

if [[ -z "${(@)explicit_file_to_load}" ]]; then
	explicit_file_to_load+=( ${plugin_path}/*.plugin.zsh(N) )
fi

# load file
if [[ -n "${(@)explicit_file_to_load}" ]]; then
	for file in ${(@)explicit_file_to_load}; do
		source ${file}
	done
fi

if [[ "${wait_condition}" == "idle" ]]; then
	eval ".zsh-defer.${1/\//--}.source() { \
		source "${(@)explicit_file_to_load}"; \
		zsh_loaded_plugins+=( "${plugin_id}" ); \
	}"
	zsh-defer .zsh-defer.${1/\//--}.source
else
	source ${(@)explicit_file_to_load}
	zsh_loaded_plugins+=( "${plugin_id}" )
fi
