#!/usr/bin/env zsh

# first argument should be always
local plugin_home="${ZUTILS[PLUGINS_DIR]}/${1/\//--}"
local plugin_id=${1}
shift

# mirror plugin if not exist yet
if [[ ! -d "${plugin_home}" ]]; then
    revolver start "Adding ${plugin_id} package.."

    case ${plugin_id} in
        (@*/*)
            local scoped_loader=".zu-fn-modif-source-${${plugin_id:h}/@/}"
            (( ! $+functions[scoped_loader] )) || scoped_loader=".zu-fn-modif-source-null"
            eval $scoped_loader ${plugin_id}
        ;;
        (*/*)
            .zu-fn-modif-source-github ${plugin_id}
        ;;
    esac

	.zu-zcompile ${plugin_id}

    revolver stop
    echo "${fg_bold[cyan]}✔${reset_color} Added ${fg_bold[blue]}${plugin_id}${reset_color} package..."
fi



while [[ -n "$@" ]]; do
    case $1 in
		(wait*)
			local namespace=".zu-fn-mod--wait--"
			local fns=(${(Mk)functions:#.zu-fn-mod--wait--*})
			for fn in $fns; do
				$fn ${1/wait/}
				[[ $? -eq 0 ]] && break
			done
		;;
        (pick*) .zu-fn-modif-pick ${1/pick/};;
    esac
    shift
done


# load plugin
if [[ -d "${plugin_home}" ]]; then
    .zu-source-plugin ${plugin_id}
fi

unset plugin_home
unset plugin_id
